import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  fr: {
    home: 'Accueil',
    nutrition: 'Nutrition',
    workout: 'Entraînement',
    run: 'Course',
    messages: 'Messages',
    settings: 'Réglages',
    profile: 'Profil',
    greeting_morning: 'Bonjour',
    greeting_afternoon: 'Bon après-midi',
    greeting_evening: 'Bonsoir',
    calories_today: "KCAL · AUJOURD'HUI",
    to_goal: 'restant',
    steps: 'PAS',
    water: 'EAU',
    todays_workouts: 'SÉANCES DU JOUR',
    view_all: 'VOIR TOUT',
    last_sleep: 'SOMMEIL CETTE NUIT',
    my_goals: 'MES OBJECTIFS →',
    breakfast: 'Petit-déjeuner',
    lunch: 'Déjeuner',
    dinner: 'Dîner',
    snack: 'Snack',
    add_food: 'AJOUTER UN ALIMENT',
    search_food: 'Rechercher un aliment...',
    quantity: 'Quantité (g)',
    add_to_meal: 'AJOUTER AU REPAS',
    scan: 'SCANNER',
    active_session: 'SÉANCE EN COURS',
    exercises: 'EXERCICES',
    add: '+ AJOUTER',
    add_set: '+ AJOUTER UNE SÉRIE',
    finish_workout: 'TERMINER LA SÉANCE',
    home_exercises: 'Exercices Maison',
    gym_exercises: 'Exercices Salle',
    outdoor_exercises: 'Exercices Dehors',
    bodyweight: 'Bodyweight · Sans équipement',
    machines: 'Machines · Charges libres',
    outdoor: 'Running · Calisthenics · HIIT',
    search_exercise: 'Rechercher un exercice...',
    added: '✓ AJOUTÉ',
    add_btn: '+ AJOUTER',
    in_progress: 'EN COURS',
    reps: 'reps',
    kg: 'kg',
    distance: 'DISTANCE',
    pace: 'ALLURE',
    duration: 'DURÉE',
    elevation: 'DÉNIVELÉ',
    heart_rate: 'FRÉQ. CARDIAQUE',
    calories_burned: 'CALORIES',
    start: 'START',
    stop: 'STOP',
    gps_strong: 'GPS · Signal fort',
    pace_per_km: 'ALLURE PAR KM',
    best_pace: 'Meilleure allure',
    this_week: 'CETTE SEMAINE',
    of_target: "DE L'OBJECTIF",
    cups: 'verres',
    ml_each: 'ml chacun',
    todays_log: 'JOURNAL DU JOUR',
    custom: 'Personnalisé',
    quality_good: 'QUALITÉ · BON',
    quality_fair: 'QUALITÉ · MOYEN',
    quality_poor: 'QUALITÉ · MAUVAIS',
    bedtime_wake: 'COUCHER → RÉVEIL',
    this_week_sleep: 'CETTE SEMAINE',
    avg: 'MOY',
    add_sleep: 'AJOUTER UNE ENTRÉE SOMMEIL',
    weekly_recap: 'BILAN SEMAINE',
    total_kcal: 'KCAL TOTAL',
    total_steps: 'PAS TOTAL',
    distance_run: 'KM COURUS',
    workouts_done: 'SÉANCES',
    avg_sleep: 'SOMMEIL MOY.',
    daily_calories: 'CALORIES / JOUR',
    goal: 'Objectif',
    ai_coach_title: 'AI Coach',
    powered_by: 'Powered by ON AIR',
    chat_placeholder: 'Pose une question à ton coach...',
    analyze_week: 'Analyse ma semaine',
    program_tomorrow: 'Programme pour demain',
    weak_points: 'Mes points faibles',
    nutrition_today: 'Nutrition du jour',
    typing: 'Le coach répond...',
    take_photo: 'PRENDRE UNE PHOTO',
    gallery: 'CHOISIR DANS LA PELLICULE',
    scan_barcode: 'SCANNER UN CODE-BARRES',
    analyzing: 'Claude analyse ton repas...',
    identifying: 'Identification du produit...',
    few_seconds: 'Quelques secondes',
    not_recognized: 'Reconnaissance impossible. Réessaie avec une meilleure photo.',
    retry: 'RECOMMENCER',
    settings_title: 'Paramètres',
    profile_section: 'PROFIL',
    first_name: 'Prénom',
    email: 'Email',
    weight: 'Poids (kg)',
    height: 'Taille (cm)',
    goals_section: 'OBJECTIFS',
    calories_day: 'Calories/jour',
    proteins: 'Protéines (g)',
    water_goal: 'Eau (ml)',
    steps_goal: 'Pas/jour',
    notifications_section: 'NOTIFICATIONS',
    hydration_reminder: 'Rappel hydratation',
    workout_reminder: 'Rappel séance',
    weekly_recap_notif: 'Bilan hebdo',
    account_section: 'COMPTE',
    language_section: 'LANGUE',
    save_goals: 'ENREGISTRER LES OBJECTIFS',
    logout: 'SE DÉCONNECTER',
    login_title: 'Connexion',
    signup_title: 'Inscription',
    login_tab: 'CONNEXION',
    signup_tab: 'INSCRIPTION',
    connect_btn: 'SE CONNECTER',
    signup_btn: 'CRÉER MON COMPTE',
    first_name_placeholder: 'Prénom',
    email_placeholder: 'ton@email.com',
    password_placeholder: '••••••••',
    confirm_password: 'Confirmer mot de passe',
    access_code: "Code d'accès ON AIR",
    wrong_credentials: 'Email ou mot de passe incorrect',
    forgot_password_link: 'Mot de passe oublié ?',
    reset_password_title: 'Mot de passe oublié',
    reset_password_subtitle: 'Entre ton email, on t’envoie un lien pour le réinitialiser.',
    send_reset_link_btn: 'ENVOYER LE LIEN',
    reset_email_sent: 'Email envoyé. Vérifie ta boîte de réception.',
    new_password_placeholder: 'Nouveau mot de passe',
    update_password_btn: 'ENREGISTRER LE MOT DE PASSE',
    password_updated_success: 'Mot de passe mis à jour. Tu peux te connecter.',
    back_to_login_btn: 'Retour à la connexion',
    passwords_no_match: 'Les mots de passe ne correspondent pas',
    invalid_code: 'Code invalide. Contacte ton coach.',
    email_exists: 'Email déjà utilisé',
    welcome_toast: 'Bienvenue',
    account_created: 'Ton compte ON AIR est créé.',
    goal_reached: 'OBJECTIF ATTEINT',
    well_done: 'Bien joué',
    continue_btn: 'CONTINUER',
    coach_dashboard: 'Tableau de bord',
    my_clients: 'MES CLIENTS',
    see_all_clients: 'VOIR TOUS MES CLIENTS',
    active_clients: 'Clients actifs',
    sessions_month: 'Séances ce mois',
    alerts: 'Alertes',
    avg_progress: 'Avg progression',
    needs_attention: 'NÉCESSITE ATTENTION',
    see_profile: 'VOIR PROFIL',
    generate_analysis: 'GÉNÉRER ANALYSE IA',
    send_message: 'ENVOYER UN MESSAGE',
    assign_goal: '+ ASSIGNER UN OBJECTIF',
    last_seen: 'Dernière visite',
    library: 'BIBLIOTHÈQUE',
    sessions_week: 'Séances cette semaine',
    today_meals: "REPAS D'AUJOURD'HUI",
    activity: 'ACTIVITÉ',
    shortcuts: 'RACCOURCIS',
    ai_coach_card: 'TON COACH IA',
    ai_coach_sub: 'Questions nutrition, programme, analyse',
    summary: 'RÉSUMÉ',
    added_to_session: 'Ajouté à ta séance ✓',
    recognize_food: 'Reconnaître un aliment',
    add_food_title: 'Ajouter un aliment',
    see_progress: 'Voyons où tu en es.',
    weekly_sessions: 'SÉANCES CETTE SEMAINE',
  },

  en: {
    home: 'Home',
    nutrition: 'Nutrition',
    workout: 'Workout',
    run: 'Run',
    messages: 'Messages',
    settings: 'Settings',
    profile: 'Profile',
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    calories_today: 'KCAL · TODAY',
    to_goal: 'to goal',
    steps: 'STEPS',
    water: 'WATER',
    todays_workouts: "TODAY'S WORKOUTS",
    view_all: 'VIEW ALL',
    last_sleep: "LAST NIGHT'S SLEEP",
    my_goals: 'MY GOALS →',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    add_food: 'ADD FOOD',
    search_food: 'Search food...',
    quantity: 'Quantity (g)',
    add_to_meal: 'ADD TO MEAL',
    scan: 'SCAN',
    active_session: 'ACTIVE SESSION',
    exercises: 'EXERCISES',
    add: '+ ADD',
    add_set: '+ ADD SET',
    finish_workout: 'FINISH WORKOUT',
    home_exercises: 'Home Exercises',
    gym_exercises: 'Gym Exercises',
    outdoor_exercises: 'Outdoor Exercises',
    bodyweight: 'Bodyweight · No equipment',
    machines: 'Machines · Free weights',
    outdoor: 'Running · Calisthenics · HIIT',
    search_exercise: 'Search exercise...',
    added: '✓ ADDED',
    add_btn: '+ ADD',
    in_progress: 'IN PROGRESS',
    reps: 'reps',
    kg: 'kg',
    distance: 'DISTANCE',
    pace: 'PACE',
    duration: 'DURATION',
    elevation: 'ELEVATION',
    heart_rate: 'HEART RATE',
    calories_burned: 'CALORIES',
    start: 'START',
    stop: 'STOP',
    gps_strong: 'GPS · Strong signal',
    pace_per_km: 'PACE PER KM',
    best_pace: 'Best pace',
    this_week: 'THIS WEEK',
    of_target: 'OF TARGET',
    cups: 'cups',
    ml_each: 'ml each',
    todays_log: "TODAY'S LOG",
    custom: 'Custom',
    quality_good: 'QUALITY · GOOD',
    quality_fair: 'QUALITY · FAIR',
    quality_poor: 'QUALITY · POOR',
    bedtime_wake: 'BEDTIME → WAKE',
    this_week_sleep: 'THIS WEEK',
    avg: 'AVG',
    add_sleep: 'ADD SLEEP ENTRY',
    weekly_recap: 'WEEKLY RECAP',
    total_kcal: 'TOTAL KCAL',
    total_steps: 'TOTAL STEPS',
    distance_run: 'DISTANCE RUN',
    workouts_done: 'WORKOUTS',
    avg_sleep: 'AVG SLEEP',
    daily_calories: 'DAILY CALORIES',
    goal: 'Goal',
    ai_coach_title: 'AI Coach',
    powered_by: 'Powered by ON AIR',
    chat_placeholder: 'Ask your coach...',
    analyze_week: 'Analyze my week',
    program_tomorrow: "Tomorrow's program",
    weak_points: 'My weak points',
    nutrition_today: "Today's nutrition",
    typing: 'Coach is typing...',
    take_photo: 'TAKE A PHOTO',
    gallery: 'CHOOSE FROM GALLERY',
    scan_barcode: 'SCAN BARCODE',
    analyzing: 'Claude is analyzing your meal...',
    identifying: 'Identifying product...',
    few_seconds: 'A few seconds',
    not_recognized: 'Recognition failed. Try a better photo.',
    retry: 'TRY AGAIN',
    settings_title: 'Settings',
    profile_section: 'PROFILE',
    first_name: 'First name',
    email: 'Email',
    weight: 'Weight (kg)',
    height: 'Height (cm)',
    goals_section: 'GOALS',
    calories_day: 'Calories/day',
    proteins: 'Proteins (g)',
    water_goal: 'Water (ml)',
    steps_goal: 'Steps/day',
    notifications_section: 'NOTIFICATIONS',
    hydration_reminder: 'Hydration reminder',
    workout_reminder: 'Workout reminder',
    weekly_recap_notif: 'Weekly recap',
    account_section: 'ACCOUNT',
    language_section: 'LANGUAGE',
    save_goals: 'SAVE GOALS',
    logout: 'LOG OUT',
    login_title: 'Login',
    signup_title: 'Sign up',
    login_tab: 'LOGIN',
    signup_tab: 'SIGN UP',
    connect_btn: 'LOG IN',
    signup_btn: 'CREATE ACCOUNT',
    first_name_placeholder: 'First name',
    email_placeholder: 'your@email.com',
    password_placeholder: '••••••••',
    confirm_password: 'Confirm password',
    access_code: 'ON AIR access code',
    wrong_credentials: 'Wrong email or password',
    forgot_password_link: 'Forgot password?',
    reset_password_title: 'Forgot password',
    reset_password_subtitle: 'Enter your email and we’ll send you a reset link.',
    send_reset_link_btn: 'SEND RESET LINK',
    reset_email_sent: 'Email sent. Check your inbox.',
    new_password_placeholder: 'New password',
    update_password_btn: 'SAVE NEW PASSWORD',
    password_updated_success: 'Password updated. You can now log in.',
    back_to_login_btn: 'Back to login',
    passwords_no_match: 'Passwords do not match',
    invalid_code: 'Invalid code. Contact your coach.',
    email_exists: 'Email already in use',
    welcome_toast: 'Welcome',
    account_created: 'Your ON AIR account is created.',
    goal_reached: 'GOAL REACHED',
    well_done: 'Well done',
    continue_btn: 'CONTINUE',
    coach_dashboard: 'Dashboard',
    my_clients: 'MY CLIENTS',
    see_all_clients: 'SEE ALL CLIENTS',
    active_clients: 'Active clients',
    sessions_month: 'Sessions this month',
    alerts: 'Alerts',
    avg_progress: 'Avg progress',
    needs_attention: 'NEEDS ATTENTION',
    see_profile: 'SEE PROFILE',
    generate_analysis: 'GENERATE AI ANALYSIS',
    send_message: 'SEND MESSAGE',
    assign_goal: '+ ASSIGN GOAL',
    last_seen: 'Last seen',
    library: 'LIBRARY',
    sessions_week: 'Sessions this week',
    today_meals: "TODAY'S MEALS",
    activity: 'ACTIVITY',
    shortcuts: 'SHORTCUTS',
    ai_coach_card: 'YOUR AI COACH',
    ai_coach_sub: 'Nutrition, program, analysis',
    summary: 'SUMMARY',
    added_to_session: 'Added to your session ✓',
    recognize_food: 'Recognize a food',
    add_food_title: 'Add food',
    see_progress: "Let's see where you are.",
    weekly_sessions: 'SESSIONS THIS WEEK',
  },

  es: {
    home: 'Inicio',
    nutrition: 'Nutrición',
    workout: 'Entrenamiento',
    run: 'Carrera',
    messages: 'Mensajes',
    settings: 'Ajustes',
    profile: 'Perfil',
    greeting_morning: 'Buenos días',
    greeting_afternoon: 'Buenas tardes',
    greeting_evening: 'Buenas noches',
    calories_today: 'KCAL · HOY',
    to_goal: 'para el objetivo',
    steps: 'PASOS',
    water: 'AGUA',
    todays_workouts: 'ENTRENAMIENTOS DE HOY',
    view_all: 'VER TODO',
    last_sleep: 'SUEÑO ANOCHE',
    my_goals: 'MIS OBJETIVOS →',
    breakfast: 'Desayuno',
    lunch: 'Almuerzo',
    dinner: 'Cena',
    snack: 'Snack',
    add_food: 'AÑADIR ALIMENTO',
    search_food: 'Buscar alimento...',
    quantity: 'Cantidad (g)',
    add_to_meal: 'AÑADIR A LA COMIDA',
    scan: 'ESCANEAR',
    active_session: 'SESIÓN ACTIVA',
    exercises: 'EJERCICIOS',
    add: '+ AÑADIR',
    add_set: '+ AÑADIR SERIE',
    finish_workout: 'TERMINAR SESIÓN',
    home_exercises: 'Ejercicios en Casa',
    gym_exercises: 'Ejercicios Gimnasio',
    outdoor_exercises: 'Ejercicios Exterior',
    bodyweight: 'Peso corporal · Sin equipamiento',
    machines: 'Máquinas · Pesas libres',
    outdoor: 'Running · Calistenia · HIIT',
    search_exercise: 'Buscar ejercicio...',
    added: '✓ AÑADIDO',
    add_btn: '+ AÑADIR',
    in_progress: 'EN CURSO',
    reps: 'reps',
    kg: 'kg',
    distance: 'DISTANCIA',
    pace: 'RITMO',
    duration: 'DURACIÓN',
    elevation: 'DESNIVEL',
    heart_rate: 'FREC. CARDÍACA',
    calories_burned: 'CALORÍAS',
    start: 'INICIAR',
    stop: 'PARAR',
    gps_strong: 'GPS · Señal fuerte',
    pace_per_km: 'RITMO POR KM',
    best_pace: 'Mejor ritmo',
    this_week: 'ESTA SEMANA',
    of_target: 'DEL OBJETIVO',
    cups: 'vasos',
    ml_each: 'ml cada uno',
    todays_log: 'REGISTRO DE HOY',
    custom: 'Personalizado',
    quality_good: 'CALIDAD · BUENA',
    quality_fair: 'CALIDAD · REGULAR',
    quality_poor: 'CALIDAD · MALA',
    bedtime_wake: 'DORMIR → DESPERTAR',
    this_week_sleep: 'ESTA SEMANA',
    avg: 'PROM',
    add_sleep: 'AÑADIR ENTRADA DE SUEÑO',
    weekly_recap: 'RESUMEN SEMANAL',
    total_kcal: 'KCAL TOTAL',
    total_steps: 'PASOS TOTAL',
    distance_run: 'KM CORRIDOS',
    workouts_done: 'SESIONES',
    avg_sleep: 'SUEÑO PROM.',
    daily_calories: 'CALORÍAS / DÍA',
    goal: 'Objetivo',
    ai_coach_title: 'Coach IA',
    powered_by: 'Impulsado por ON AIR',
    chat_placeholder: 'Pregunta a tu coach...',
    analyze_week: 'Analiza mi semana',
    program_tomorrow: 'Programa de mañana',
    weak_points: 'Mis puntos débiles',
    nutrition_today: 'Nutrición de hoy',
    typing: 'El coach está escribiendo...',
    take_photo: 'TOMAR UNA FOTO',
    gallery: 'ELEGIR DE LA GALERÍA',
    scan_barcode: 'ESCANEAR CÓDIGO DE BARRAS',
    analyzing: 'Claude analiza tu comida...',
    identifying: 'Identificando producto...',
    few_seconds: 'Unos segundos',
    not_recognized: 'Reconocimiento fallido. Intenta con mejor foto.',
    retry: 'REINTENTAR',
    settings_title: 'Ajustes',
    profile_section: 'PERFIL',
    first_name: 'Nombre',
    email: 'Email',
    weight: 'Peso (kg)',
    height: 'Altura (cm)',
    goals_section: 'OBJETIVOS',
    calories_day: 'Calorías/día',
    proteins: 'Proteínas (g)',
    water_goal: 'Agua (ml)',
    steps_goal: 'Pasos/día',
    notifications_section: 'NOTIFICACIONES',
    hydration_reminder: 'Recordatorio hidratación',
    workout_reminder: 'Recordatorio sesión',
    weekly_recap_notif: 'Resumen semanal',
    account_section: 'CUENTA',
    language_section: 'IDIOMA',
    save_goals: 'GUARDAR OBJETIVOS',
    logout: 'CERRAR SESIÓN',
    login_title: 'Iniciar sesión',
    signup_title: 'Registro',
    login_tab: 'INICIAR SESIÓN',
    signup_tab: 'REGISTRARSE',
    connect_btn: 'INICIAR SESIÓN',
    signup_btn: 'CREAR CUENTA',
    first_name_placeholder: 'Nombre',
    email_placeholder: 'tu@email.com',
    password_placeholder: '••••••••',
    confirm_password: 'Confirmar contraseña',
    access_code: 'Código de acceso ON AIR',
    wrong_credentials: 'Email o contraseña incorrectos',
    forgot_password_link: '¿Olvidaste tu contraseña?',
    reset_password_title: 'Contraseña olvidada',
    reset_password_subtitle: 'Escribe tu email y te enviamos un enlace para restablecerla.',
    send_reset_link_btn: 'ENVIAR ENLACE',
    reset_email_sent: 'Email enviado. Revisa tu bandeja de entrada.',
    new_password_placeholder: 'Nueva contraseña',
    update_password_btn: 'GUARDAR CONTRASEÑA',
    password_updated_success: 'Contraseña actualizada. Ya puedes iniciar sesión.',
    back_to_login_btn: 'Volver al inicio de sesión',
    passwords_no_match: 'Las contraseñas no coinciden',
    invalid_code: 'Código inválido. Contacta tu coach.',
    email_exists: 'Email ya en uso',
    welcome_toast: 'Bienvenido',
    account_created: 'Tu cuenta ON AIR está creada.',
    goal_reached: 'OBJETIVO ALCANZADO',
    well_done: 'Bien hecho',
    continue_btn: 'CONTINUAR',
    coach_dashboard: 'Panel de control',
    my_clients: 'MIS CLIENTES',
    see_all_clients: 'VER TODOS MIS CLIENTES',
    active_clients: 'Clientes activos',
    sessions_month: 'Sesiones este mes',
    alerts: 'Alertas',
    avg_progress: 'Progreso prom.',
    needs_attention: 'NECESITA ATENCIÓN',
    see_profile: 'VER PERFIL',
    generate_analysis: 'GENERAR ANÁLISIS IA',
    send_message: 'ENVIAR MENSAJE',
    assign_goal: '+ ASIGNAR OBJETIVO',
    last_seen: 'Última visita',
    library: 'BIBLIOTECA',
    sessions_week: 'Sesiones esta semana',
    today_meals: 'COMIDAS DE HOY',
    activity: 'ACTIVIDAD',
    shortcuts: 'ATAJOS',
    ai_coach_card: 'TU COACH IA',
    ai_coach_sub: 'Nutrición, programa, análisis',
    summary: 'RESUMEN',
    added_to_session: 'Añadido a tu sesión ✓',
    recognize_food: 'Identificar un alimento',
    add_food_title: 'Añadir alimento',
    see_progress: 'Veamos cómo estás.',
    weekly_sessions: 'SESIONES ESTA SEMANA',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('onair_lang') || 'fr';
  });

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('onair_lang', newLang);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['fr'][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
