import { createContext, useContext, useState } from 'react';

const LanguageContext = createContext(null);

export const TRANSLATIONS = {
  fr: {
    workout: 'Entraînement',
    greeting_morning: 'Bonjour',
    greeting_afternoon: 'Bon après-midi',
    greeting_evening: 'Bonsoir',
    steps: 'PAS',
    breakfast: 'Petit-déjeuner',
    lunch: 'Déjeuner',
    dinner: 'Dîner',
    snack: 'Snack',
    quantity: 'Quantité (g)',
    add_to_meal: 'AJOUTER AU REPAS',
    add: '+ AJOUTER',
    home_exercises: 'Exercices Maison',
    gym_exercises: 'Exercices Salle',
    outdoor_exercises: 'Exercices Street Workout',
    bodyweight: 'Bodyweight · Sans équipement',
    machines: 'Machines · Charges libres',
    outdoor: 'Running · Calisthenics · HIIT',
    search_exercise: 'Rechercher un exercice...',
    added: '✓ AJOUTÉ',
    add_btn: '+ AJOUTER',
    distance_run: 'KM COURUS',
    workouts_done: 'SÉANCES',
    avg_sleep: 'SOMMEIL MOY.',
    daily_calories: 'CALORIES / JOUR',
    goal: 'Objectif',
    ai_coach_title: 'AI Coach',
    powered_by: 'Powered by VOLTA',
    chat_placeholder: 'Pose une question à ton coach...',
    take_photo: 'PRENDRE UNE PHOTO',
    gallery: 'CHOISIR DANS LA PELLICULE',
    scan_barcode: 'SCANNER UN CODE-BARRES',
    analyzing: 'Claude analyse ton repas...',
    identifying: 'Identification du produit...',
    few_seconds: 'Quelques secondes',
    retry: 'RECOMMENCER',
    settings_title: 'Paramètres',
    profile_section: 'PROFIL',
    first_name: 'Prénom',
    email: 'Email',
    weight: 'Poids (kg)',
    height: 'Taille (cm)',
    goals_section: 'OBJECTIFS',
    calories_day: 'Calories/jour',
    proteins: 'Protéines (g)',
    notifications_section: 'NOTIFICATIONS',
    account_section: 'COMPTE',
    language_section: 'LANGUE',
    save_goals: 'ENREGISTRER LES OBJECTIFS',
    logout: 'SE DÉCONNECTER',
    login_tab: 'CONNEXION',
    signup_tab: 'INSCRIPTION',
    connect_btn: 'SE CONNECTER',
    signup_btn: 'CRÉER MON COMPTE',
    first_name_placeholder: 'Prénom',
    email_placeholder: 'ton@email.com',
    password_placeholder: '••••••••',
    confirm_password: 'Confirmer mot de passe',
    access_code: "Code d'accès VOLTA",
    forgot_password_link: 'Mot de passe oublié ?',
    reset_password_title: 'Mot de passe oublié',
    reset_password_subtitle: 'Entre ton email, on t’envoie un lien pour le réinitialiser.',
    send_reset_link_btn: 'ENVOYER LE LIEN',
    reset_email_sent: 'Email envoyé. Vérifie ta boîte de réception.',
    new_password_placeholder: 'Nouveau mot de passe',
    update_password_btn: 'ENREGISTRER LE MOT DE PASSE',
    password_updated_success: 'Mot de passe mis à jour. Tu peux te connecter.',
    back_to_login_btn: 'Retour à la connexion',
    passwords_no_match: 'Les mots de passe ne correspondent pas',
    invalid_code: 'Code invalide. Contacte ton coach.',
    welcome_toast: 'Bienvenue',
    account_created: 'Ton compte VOLTA est créé.',
    library: 'BIBLIOTHÈQUE',
    sessions_week: 'Séances cette semaine',
    today_meals: "REPAS D'AUJOURD'HUI",
    activity: 'ACTIVITÉ',
    summary: 'RÉSUMÉ',
    recognize_food: 'Reconnaître un aliment',
    add_food_title: 'Ajouter un aliment',
  },

  en: {
    workout: 'Workout',
    greeting_morning: 'Good morning',
    greeting_afternoon: 'Good afternoon',
    greeting_evening: 'Good evening',
    steps: 'STEPS',
    breakfast: 'Breakfast',
    lunch: 'Lunch',
    dinner: 'Dinner',
    snack: 'Snack',
    quantity: 'Quantity (g)',
    add_to_meal: 'ADD TO MEAL',
    add: '+ ADD',
    home_exercises: 'Home Exercises',
    gym_exercises: 'Gym Exercises',
    outdoor_exercises: 'Street Workout Exercises',
    bodyweight: 'Bodyweight · No equipment',
    machines: 'Machines · Free weights',
    outdoor: 'Running · Calisthenics · HIIT',
    search_exercise: 'Search exercise...',
    added: '✓ ADDED',
    add_btn: '+ ADD',
    distance_run: 'DISTANCE RUN',
    workouts_done: 'WORKOUTS',
    avg_sleep: 'AVG SLEEP',
    daily_calories: 'DAILY CALORIES',
    goal: 'Goal',
    ai_coach_title: 'AI Coach',
    powered_by: 'Powered by VOLTA',
    chat_placeholder: 'Ask your coach...',
    take_photo: 'TAKE A PHOTO',
    gallery: 'CHOOSE FROM GALLERY',
    scan_barcode: 'SCAN BARCODE',
    analyzing: 'Claude is analyzing your meal...',
    identifying: 'Identifying product...',
    few_seconds: 'A few seconds',
    retry: 'TRY AGAIN',
    settings_title: 'Settings',
    profile_section: 'PROFILE',
    first_name: 'First name',
    email: 'Email',
    weight: 'Weight (kg)',
    height: 'Height (cm)',
    goals_section: 'GOALS',
    calories_day: 'Calories/day',
    proteins: 'Proteins (g)',
    notifications_section: 'NOTIFICATIONS',
    account_section: 'ACCOUNT',
    language_section: 'LANGUAGE',
    save_goals: 'SAVE GOALS',
    logout: 'LOG OUT',
    login_tab: 'LOGIN',
    signup_tab: 'SIGN UP',
    connect_btn: 'LOG IN',
    signup_btn: 'CREATE ACCOUNT',
    first_name_placeholder: 'First name',
    email_placeholder: 'your@email.com',
    password_placeholder: '••••••••',
    confirm_password: 'Confirm password',
    access_code: 'VOLTA access code',
    forgot_password_link: 'Forgot password?',
    reset_password_title: 'Forgot password',
    reset_password_subtitle: 'Enter your email and we’ll send you a reset link.',
    send_reset_link_btn: 'SEND RESET LINK',
    reset_email_sent: 'Email sent. Check your inbox.',
    new_password_placeholder: 'New password',
    update_password_btn: 'SAVE NEW PASSWORD',
    password_updated_success: 'Password updated. You can now log in.',
    back_to_login_btn: 'Back to login',
    passwords_no_match: 'Passwords do not match',
    invalid_code: 'Invalid code. Contact your coach.',
    welcome_toast: 'Welcome',
    account_created: 'Your VOLTA account is created.',
    library: 'LIBRARY',
    sessions_week: 'Sessions this week',
    today_meals: "TODAY'S MEALS",
    activity: 'ACTIVITY',
    summary: 'SUMMARY',
    recognize_food: 'Recognize a food',
    add_food_title: 'Add food',
  },

  es: {
    workout: 'Entrenamiento',
    greeting_morning: 'Buenos días',
    greeting_afternoon: 'Buenas tardes',
    greeting_evening: 'Buenas noches',
    steps: 'PASOS',
    breakfast: 'Desayuno',
    lunch: 'Almuerzo',
    dinner: 'Cena',
    snack: 'Snack',
    quantity: 'Cantidad (g)',
    add_to_meal: 'AÑADIR A LA COMIDA',
    add: '+ AÑADIR',
    home_exercises: 'Ejercicios en Casa',
    gym_exercises: 'Ejercicios Gimnasio',
    outdoor_exercises: 'Ejercicios Street Workout',
    bodyweight: 'Peso corporal · Sin equipamiento',
    machines: 'Máquinas · Pesas libres',
    outdoor: 'Running · Calistenia · HIIT',
    search_exercise: 'Buscar ejercicio...',
    added: '✓ AÑADIDO',
    add_btn: '+ AÑADIR',
    distance_run: 'KM CORRIDOS',
    workouts_done: 'SESIONES',
    avg_sleep: 'SUEÑO PROM.',
    daily_calories: 'CALORÍAS / DÍA',
    goal: 'Objetivo',
    ai_coach_title: 'Coach IA',
    powered_by: 'Impulsado por VOLTA',
    chat_placeholder: 'Pregunta a tu coach...',
    take_photo: 'TOMAR UNA FOTO',
    gallery: 'ELEGIR DE LA GALERÍA',
    scan_barcode: 'ESCANEAR CÓDIGO DE BARRAS',
    analyzing: 'Claude analiza tu comida...',
    identifying: 'Identificando producto...',
    few_seconds: 'Unos segundos',
    retry: 'REINTENTAR',
    settings_title: 'Ajustes',
    profile_section: 'PERFIL',
    first_name: 'Nombre',
    email: 'Email',
    weight: 'Peso (kg)',
    height: 'Altura (cm)',
    goals_section: 'OBJETIVOS',
    calories_day: 'Calorías/día',
    proteins: 'Proteínas (g)',
    notifications_section: 'NOTIFICACIONES',
    account_section: 'CUENTA',
    language_section: 'IDIOMA',
    save_goals: 'GUARDAR OBJETIVOS',
    logout: 'CERRAR SESIÓN',
    login_tab: 'INICIAR SESIÓN',
    signup_tab: 'REGISTRARSE',
    connect_btn: 'INICIAR SESIÓN',
    signup_btn: 'CREAR CUENTA',
    first_name_placeholder: 'Nombre',
    email_placeholder: 'tu@email.com',
    password_placeholder: '••••••••',
    confirm_password: 'Confirmar contraseña',
    access_code: 'Código de acceso VOLTA',
    forgot_password_link: '¿Olvidaste tu contraseña?',
    reset_password_title: 'Contraseña olvidada',
    reset_password_subtitle: 'Escribe tu email y te enviamos un enlace para restablecerla.',
    send_reset_link_btn: 'ENVIAR ENLACE',
    reset_email_sent: 'Email enviado. Revisa tu bandeja de entrada.',
    new_password_placeholder: 'Nueva contraseña',
    update_password_btn: 'GUARDAR CONTRASEÑA',
    password_updated_success: 'Contraseña actualizada. Ya puedes iniciar sesión.',
    back_to_login_btn: 'Volver al inicio de sesión',
    passwords_no_match: 'Las contraseñas no coinciden',
    invalid_code: 'Código inválido. Contacta tu coach.',
    welcome_toast: 'Bienvenido',
    account_created: 'Tu cuenta VOLTA está creada.',
    library: 'BIBLIOTECA',
    sessions_week: 'Sesiones esta semana',
    today_meals: 'COMIDAS DE HOY',
    activity: 'ACTIVIDAD',
    summary: 'RESUMEN',
    recognize_food: 'Identificar un alimento',
    add_food_title: 'Añadir alimento',
  },
};

export const LanguageProvider = ({ children }) => {
  const [lang, setLang] = useState(() => {
    return localStorage.getItem('onair_lang') || 'fr';
  });

  const setLanguage = (newLang) => {
    setLang(newLang);
    localStorage.setItem('onair_lang', newLang);
  };

  const t = (key) => TRANSLATIONS[lang]?.[key] || TRANSLATIONS['fr'][key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => useContext(LanguageContext);
